development:
  adapter: sqlite3
  database: <%= File.join(ENV['APP_ROOT'] || Dir.pwd, 'db', 'development.sqlite3') %>
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: <%= File.join(ENV['APP_ROOT'] || Dir.pwd, 'db', 'test.sqlite3') %>
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>
